# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Environment Properties
minecraft_version=1.21
minecraft_version_range=[1.21,1.22)

## Mod Properties
mod_id=sereneseasonsphc2crops
mod_name=Serene Seasons - Pam's HarvestCraft 2: Crops Compat
mod_license=MIT License
mod_version=0.6.9
mod_group_id=darkorg.sereneseasonsphc2crops
mod_authors=Darkorg
mod_description=Grow your crops in their respective seasons!

# Forge Properties (disabled - no Forge version for 1.21)
#forge_version=49.0.53
#forge_version_range=[49,)
#forge_loader_version_range=[49,)

# NeoForge Properties
neo_version=21.0.167
neo_version_range=[21.0,)
neo_loader_version_range=[4,)

# Parchment mappings
parchment_version=2024.07.28

# CurseMaven dependencies (Forge) - disabled
#forge_sereneseasons_version=5206531
#forge_pamhc2crops_version=5195161
#forge_glitchcore_version=5088441

# CurseMaven dependencies (NeoForge)
neoforge_sereneseasons_version=5613014
neoforge_pamhc2crops_version=5581644
neoforge_glitchcore_version=5645390
