# Mod info
modId=sereneseasonsphc2crops
mod_version=0.6.9
mod_author=Darkorg
mod_displayName=Serene Seasons - Pam's HarvestCraft 2: Crops Compat

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[4,)

# Parchment mappings
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# CurseForge file IDs for NeoForge 1.21.1 versions
glitchcore_version=8109792
sereneseasons_version=6182596
pamhc2crops_version=8064883

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
