modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/serene-seasons-pams-harvestcraft-2-crops-compat/issues"
[[mods]]
modId = "sereneseasonsphc2crops"
version = "${file.jarVersion}"
displayName = "Serene Seasons - Pam's HarvestCraft 2 - Crops Compat"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/serene-seasons-pams-harvestcraft-2-crops-compat"
logoFile = "sereneseasonsphc2crops.png"
credits = "Thanks for this mod goes to Java and the Forge Team."
authors = "Darkorg"
description = '''Grow your crops in their respective seasons!'''

[[dependencies.sereneseasonsphc2crops]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.16.5-4.0.1.127,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sereneseasonsphc2crops]]
modId = "pamhc2crops"
mandatory = true
versionRange = "[version,)"
ordering = "NONE"
side = "BOTH"